{% set name = "aioresponses" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aioresponses-{{ version }}.tar.gz
  sha256: 794b3e04837a683fd2c0c099bdf77f8d7ecdd284bc2c15203003518bf5cb8da8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pbr
    - pip
  run:
    - python >=3.7
    - aiohttp >=3.3.0,<4
    - packaging

test:
  imports:
    - aioresponses
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pnuckowski/aioresponses
  summary: Mock out requests made by ClientSession from aiohttp package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
