{% set name = "aioresponses" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aioresponses-{{ version }}.tar.gz
  sha256: f795d9dbda2d61774840e7e32f5366f45752d1adc1b74c9362afd017296c7ee1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pbr
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.3.0,<4
    - packaging

test:
  imports:
    - aioresponses
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pnuckowski/aioresponses
  summary: Mock out requests made by ClientSession from aiohttp package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
