{% set name = "aioresponses" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aioresponses-{{ version }}.tar.gz
  sha256: b861cdfe5dc58f3b8afac7b0a6973d5d7b2cb608dd0f6253d16b8ee8eaf6df11

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pbr
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.3.0,<4
    - packaging

test:
  imports:
    - aioresponses
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pnuckowski/aioresponses
  summary: Mock out requests made by ClientSession from aiohttp package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
